name: fsspec-reference-maker
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - pip
  - fsspec-reference-maker
  - fsspec
  - s3fs
  - xarray
  - matplotlib
  - ujson
  - dask
  - h5py
  - jupyterlab
  - nodejs
  - metpy
  - cartopy
  - cfgrib
  - eccodes
  - numpy<=1.20.0
  - pip:
    - dask_labextension
    - hvplot
    - geoviews
    - datashader
    - bokeh
